Repository AY2324S1-CS2103T-F11-2/tp, pull requests merged in 2023-11, with the labels that each got.

#165 Fix `guest edit` bug
  src/main/java/wedlog/address/logic/parser/GuestEditCommandParser.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/parser/GuestEditCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/VendorEditCommandParserTest.java
Labels: type.Bug

#163 Change dietary requirements statistics panel
  codecov.yml
  src/main/java/wedlog/address/commons/core/GuiSettings.java
  src/main/java/wedlog/address/model/DietaryRequirementStatistics.java
  src/main/java/wedlog/address/model/person/Guest.java
  src/main/java/wedlog/address/model/person/UniqueGuestList.java
  src/main/java/wedlog/address/model/tag/DietaryRequirement.java
  src/main/java/wedlog/address/ui/CommandBox.java
  src/main/java/wedlog/address/ui/DietaryPanel.java
  src/main/java/wedlog/address/ui/GuestListPanel.java
  src/main/java/wedlog/address/ui/MainWindow.java
  src/main/java/wedlog/address/ui/RsvpPanel.java
  src/main/java/wedlog/address/ui/StatisticsPanel.java
  src/main/java/wedlog/address/ui/VendorListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DietaryPanel.fxml
  src/main/resources/view/GuestListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsPanel.fxml
  src/main/resources/view/VendorListPanel.fxml
  src/test/java/wedlog/address/model/person/GuestTest.java
  src/test/java/wedlog/address/model/person/UniqueGuestListTest.java
  src/test/java/wedlog/address/model/tag/DietaryRequirementTest.java
  src/test/java/wedlog/address/testutil/GuestBuilder.java
Labels: priority.High

#166 Update filter feature
  docs/UserGuide.md
  src/main/java/wedlog/address/logic/commands/GuestFilterCommand.java
  src/main/java/wedlog/address/logic/commands/VendorFilterCommand.java
  src/main/java/wedlog/address/logic/parser/GuestFilterCommandParser.java
  src/main/java/wedlog/address/logic/parser/VendorFilterCommandParser.java
  src/main/java/wedlog/address/model/person/AddressPredicate.java
  src/main/java/wedlog/address/model/person/EmailPredicate.java
  src/main/java/wedlog/address/model/person/GuestRsvpPredicate.java
  src/main/java/wedlog/address/model/person/GuestTablePredicate.java
  src/main/java/wedlog/address/model/person/NamePredicate.java
  src/main/java/wedlog/address/model/person/PhonePredicate.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/GuestFilterCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorFilterCommandTest.java
  src/test/java/wedlog/address/logic/parser/GuestFilterCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/VendorFilterCommandParserTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/person/AddressPredicateTest.java
  src/test/java/wedlog/address/model/person/EmailPredicateTest.java
  src/test/java/wedlog/address/model/person/GuestRsvpPredicateTest.java
  src/test/java/wedlog/address/model/person/GuestTablePredicateTest.java
  src/test/java/wedlog/address/model/person/NamePredicateTest.java
  src/test/java/wedlog/address/model/person/PhonePredicateTest.java
  src/test/java/wedlog/address/testutil/TypicalVendors.java
Labels: priority.High

#167 Fix minor bug in diet statistics
  src/main/java/wedlog/address/model/person/UniqueGuestList.java
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/model/AddressBookTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/person/UniqueGuestListTest.java
  src/test/java/wedlog/address/testutil/TypicalGuests.java
Labels: type.Bug, severity.Low

#171 Fix exception on application startup
  src/main/java/wedlog/address/MainApp.java
  src/main/java/wedlog/address/ui/MainWindow.java
Labels: priority.High, type.Bug, severity.High

#168 Update tag fields to be allMatch
  src/main/java/wedlog/address/model/tag/GuestDietaryPredicate.java
  src/main/java/wedlog/address/model/tag/TagPredicate.java
  src/test/java/wedlog/address/model/tag/GuestDietaryPredicateTest.java
  src/test/java/wedlog/address/model/tag/TagPredicateTest.java
Labels: type.Enhancement

#173 Name: Make name equality case insensitive
  src/main/java/wedlog/address/model/person/Name.java
  src/test/java/wedlog/address/model/person/NameTest.java
  src/test/java/wedlog/address/model/person/PersonTest.java
  src/test/java/wedlog/address/model/person/VendorTest.java
Labels: priority.Medium

#176 Make minor adjustments to UG
  docs/UserGuide.md
Labels: documentation

#228 Docs: Update PPP for Samuel
  docs/team/samuelim01.md
Labels: documentation

#227 UG: Fix broken Appendix A links
  docs/UserGuide.md
Labels: documentation, severity.Medium

#234 Docs: Update PPP for Keagan
  docs/team/keaganpzh.md
Labels: documentation

#235 Docs: Update PPP for Shannon
  docs/team/tllshan.md
Labels: documentation

#245 Fix window size on startup bug
  src/main/java/wedlog/address/commons/core/GuiSettings.java
Labels: PED.FunctionalityBug

#244 Fix table number max int bug
  docs/UserGuide.md
  src/main/java/wedlog/address/model/person/TableNumber.java
  src/test/java/wedlog/address/model/person/TableNumberTest.java
Labels: PED.FunctionalityBug

#263 DG: Add code acknowledgements
  docs/DeveloperGuide.md
Labels: documentation

#262 DG: Update Appendix B
  docs/DeveloperGuide.md
Labels: documentation

#261 SampleDataUtil: Add sample guest and vendor data
  src/main/java/wedlog/address/model/util/SampleDataUtil.java
Labels: type.Task

#248 UG: Add section on Quick View panel and other improvements
  docs/UserGuide.md
  docs/images/dietary-requirements-panel.png
  docs/images/quick-view-panel.png
  docs/images/rsvp-status-panel.png
  docs/team/keaganpzh.md
Labels: documentation

#267 Update UG: Appendix A and more
  docs/UserGuide.md
Labels: documentation

#260 Remove persons from AddressBook
  docs/team/samuelim01.md
  src/main/java/wedlog/address/logic/Logic.java
  src/main/java/wedlog/address/logic/LogicManager.java
  src/main/java/wedlog/address/logic/commands/RedoCommand.java
  src/main/java/wedlog/address/logic/commands/UndoCommand.java
  src/main/java/wedlog/address/model/AddressBook.java
  src/main/java/wedlog/address/model/Model.java
  src/main/java/wedlog/address/model/ModelManager.java
  src/main/java/wedlog/address/model/ReadOnlyAddressBook.java
  src/main/java/wedlog/address/model/person/UniquePersonList.java
  src/main/java/wedlog/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/wedlog/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/wedlog/address/model/util/SampleDataUtil.java
  src/main/java/wedlog/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateGuestAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateVendorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidGuestAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidVendorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalGuestsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalVendorsAddressBook.json
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/ClearCommandTest.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
  src/test/java/wedlog/address/model/AddressBookTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/VersionedAddressBookTest.java
  src/test/java/wedlog/address/model/person/UniquePersonListTest.java
  src/test/java/wedlog/address/storage/JsonAddressBookStorageTest.java
  src/test/java/wedlog/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/wedlog/address/storage/StorageManagerTest.java
  src/test/java/wedlog/address/testutil/AddressBookBuilder.java
  src/test/java/wedlog/address/testutil/TestUtil.java
  src/test/java/wedlog/address/testutil/TypicalPersons.java
Labels: type.Task

#265 DG: Improve formatting
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#270 DG: Fix content page formatting
  docs/DeveloperGuide.md
Labels: documentation

#266 UG: improve user orientation and readability
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/tutorial/clear.png
  docs/images/tutorial/guest-add.png
  docs/images/tutorial/guest-edit.png
  docs/images/tutorial/guest-filter-0.png
  docs/images/tutorial/guest-filter-1.png
  docs/images/tutorial/guest-filter-2.png
  docs/images/tutorial/guest-filter-3.png
  docs/images/understanding-interface/dietary-requirements-panel.png
  docs/images/understanding-interface/guest-card.png
  docs/images/understanding-interface/input-output.png
  docs/images/understanding-interface/lists.png
  docs/images/understanding-interface/quick-view-panel.png
  docs/images/understanding-interface/rsvp-status-panel.png
  docs/images/understanding-interface/ui-overview.png
  docs/images/understanding-interface/vendor-card.png
Labels: documentation

#275 Branch update dg filter
  docs/DeveloperGuide.md
  docs/diagrams/FilterGuestPredicateClassDiagram.puml
  docs/diagrams/FilterGuestSequenceDiagram.puml
  docs/diagrams/FilterGuestSequenceDiagramRef.puml
  docs/diagrams/FilterPersonPredicateClassDiagram.puml
  docs/diagrams/FilterVendorSequenceDiagram.puml
  docs/diagrams/FilterVendorSequenceDiagramRef.puml
  docs/diagrams/FilterXYZSequenceDiagram.puml
  docs/diagrams/FilterXYZSequenceDiagramCreateCommandRef.puml
  docs/diagrams/FilterXYZSequenceDiagramExecuteCommandRef.puml
Labels: documentation

#274 Improve code quality
  src/main/java/wedlog/address/logic/Messages.java
  src/test/java/wedlog/address/commons/core/GuiSettingsTest.java
  src/test/java/wedlog/address/commons/util/CollectionUtilTest.java
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/VendorEditCommandTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/person/UniqueGuestListTest.java
  src/test/java/wedlog/address/model/person/UniqueVendorListTest.java
Labels: type.Task

#271 UG/DG: Fix layouts
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
  docs/images/tutorial/clear.png
  docs/images/tutorial/guest-add.png
  docs/images/tutorial/guest-edit.png
  docs/images/tutorial/guest-filter-0.png
  docs/images/tutorial/guest-filter-1.png
  docs/team/keaganpzh.md
Labels: documentation

#277 Branch update DG: Use cases
  docs/DeveloperGuide.md
Labels: documentation

#279 Delete johndoe.md
  docs/team/johndoe.md
Labels: type.Task

#280 Update version number in main app to 1.4
  src/main/java/wedlog/address/MainApp.java
Labels: type.Task

#285 Update joe PPP
  docs/team/samuelim01.md
  docs/team/wasjoe1.md
Labels: documentation

#286 Branch convert to pdf
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#288 UG: Update getting started
  docs/UserGuide.md
Labels: documentation
