Repository AY2324S1-CS2103T-F11-2/tp, pull requests merged in 2023-10, with the labels that each got.

#31 Create Vendor class
  src/main/java/seedu/address/model/person/Vendor.java
  src/test/java/seedu/address/model/person/VendorTest.java
  src/test/java/seedu/address/testutil/VendorUtil.java
Labels: enhancement

#30 Create Guest, RsvpStatus, DietaryRequirements classes
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/DietaryRequirements.java
  src/main/java/seedu/address/model/person/Guest.java
  src/main/java/seedu/address/model/person/RsvpStatus.java
  src/test/java/seedu/address/model/person/DietaryRequirementsTest.java
  src/test/java/seedu/address/model/person/GuestTest.java
  src/test/java/seedu/address/model/person/RsvpStatusTest.java
  src/test/java/seedu/address/testutil/GuestUtil.java
Labels: enhancement

#33 Add skeletal PPP (Shannon)
  docs/AboutUs.md
  docs/team/tllshan.md
Labels: documentation

#32 Update feature list of UG
  docs/UserGuide.md
Labels: documentation

#36 Update product scope in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#39 Update DG NFRs
  docs/DeveloperGuide.md
Labels: documentation

#37 update UG: view guest(s)
  docs/UserGuide.md
Labels: documentation

#40 UG: Add `vendor add` and `vendor delete`
  docs/UserGuide.md
Labels: documentation

#38 Update DG use case section
  docs/DeveloperGuide.md
Labels: documentation

#42 update DG: Glossary and Appendix
  docs/DeveloperGuide.md
Labels: documentation

#35 Add Appendix A: Miscellaneous error message to User Guide
  docs/UserGuide.md
Labels: documentation

#46 UG: Add `help`
  docs/DeveloperGuide.md
Labels: documentation

#85 DG: Fix user stories cosmetic issue
  docs/DeveloperGuide.md
Labels: type.Bug, severity.VeryLow

#94 docs: Add a favicon
  docs/favicon.ico
  docs/images/WedLogLogo.jpg
  docs/site.json
Labels: type.Bug, severity.VeryLow

#95 update UI mockup
  docs/images/Ui.png
Labels: documentation, severity.VeryLow

#97 MainApp: Bump version to 1.1.1
  src/main/java/wedlog/address/MainApp.java
Labels: type.Task

#101 Modify `Person` to have optional fields
  src/main/java/wedlog/address/logic/Messages.java
  src/main/java/wedlog/address/logic/parser/AddCommandParser.java
  src/main/java/wedlog/address/logic/parser/ParserUtil.java
  src/main/java/wedlog/address/model/person/DietaryRequirements.java
  src/main/java/wedlog/address/model/person/Guest.java
  src/main/java/wedlog/address/model/person/Person.java
  src/main/java/wedlog/address/model/person/RsvpStatus.java
  src/main/java/wedlog/address/model/person/Vendor.java
  src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
  src/main/java/wedlog/address/storage/JsonAdaptedPerson.java
  src/main/java/wedlog/address/storage/JsonAdaptedVendor.java
  src/main/java/wedlog/address/ui/PersonCard.java
  src/test/java/wedlog/address/logic/parser/AddCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/ParserUtilTest.java
  src/test/java/wedlog/address/model/person/DietaryRequirementsTest.java
  src/test/java/wedlog/address/model/person/GuestTest.java
  src/test/java/wedlog/address/model/person/PersonTest.java
  src/test/java/wedlog/address/model/person/RsvpStatusTest.java
  src/test/java/wedlog/address/model/person/VendorTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedPersonTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedVendorTest.java
  src/test/java/wedlog/address/testutil/GuestBuilder.java
  src/test/java/wedlog/address/testutil/PersonBuilder.java
  src/test/java/wedlog/address/testutil/VendorBuilder.java
Labels: priority.High

#104 Implement `GuestList` & `VendorList` commands
  src/main/java/wedlog/address/logic/commands/GuestListCommand.java
  src/main/java/wedlog/address/logic/commands/VendorListCommand.java
  src/test/java/wedlog/address/logic/commands/GuestListCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorListCommandTest.java
Labels: priority.High

#103 Implement `vendor delete`
  src/main/java/wedlog/address/logic/Messages.java
  src/main/java/wedlog/address/logic/commands/VendorAddCommand.java
  src/main/java/wedlog/address/logic/commands/VendorDeleteCommand.java
  src/main/java/wedlog/address/logic/parser/VendorCommandParser.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/VendorDeleteCommandTest.java
Labels: priority.High

#102 Implement `guest delete`
  src/main/java/wedlog/address/logic/Messages.java
  src/main/java/wedlog/address/logic/commands/GuestAddCommand.java
  src/main/java/wedlog/address/logic/commands/GuestDeleteCommand.java
  src/main/java/wedlog/address/logic/parser/GuestDeleteCommandParser.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/GuestDeleteCommandTest.java
  src/test/java/wedlog/address/logic/parser/GuestDeleteCommandParserTest.java
Labels: priority.High

#111 Fix: loading data from local storage
  src/main/java/wedlog/address/model/person/Guest.java
  src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
  src/test/java/wedlog/address/model/person/GuestTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
  src/test/java/wedlog/address/testutil/TypicalGuests.java
Labels: type.Bug, severity.High

#115 UG: Add `help` and `exit` command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: type.Bug, severity.VeryLow

#114 Create new UI and integrate all v1.2 changes
  src/main/java/wedlog/address/MainApp.java
  src/main/java/wedlog/address/commons/core/GuiSettings.java
  src/main/java/wedlog/address/logic/Logic.java
  src/main/java/wedlog/address/logic/LogicManager.java
  src/main/java/wedlog/address/logic/commands/AddCommand.java
  src/main/java/wedlog/address/logic/parser/AddCommandParser.java
  src/main/java/wedlog/address/logic/parser/AddressBookParser.java
  src/main/java/wedlog/address/model/AddressBook.java
  src/main/java/wedlog/address/model/Model.java
  src/main/java/wedlog/address/model/ModelManager.java
  src/main/java/wedlog/address/model/RsvpStatistics.java
  src/main/java/wedlog/address/model/person/UniqueGuestList.java
  src/main/java/wedlog/address/ui/GuestCard.java
  src/main/java/wedlog/address/ui/GuestListPanel.java
  src/main/java/wedlog/address/ui/MainWindow.java
  src/main/java/wedlog/address/ui/PersonListPanel.java
  src/main/java/wedlog/address/ui/StatisticsPanel.java
  src/main/java/wedlog/address/ui/VendorCard.java
  src/main/java/wedlog/address/ui/VendorListPanel.java
  src/main/resources/images/WedLogLogo.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/GuestListCard.fxml
  src/main/resources/view/GuestListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatisticsPanel.fxml
  src/main/resources/view/VendorListCard.fxml
  src/main/resources/view/VendorListPanel.fxml
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/wedlog/address/logic/commands/AddCommandTest.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
  src/test/java/wedlog/address/logic/parser/AddCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/AddressBookParserTest.java
  src/test/java/wedlog/address/model/AddressBookTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/RsvpStatisticsTest.java
  src/test/java/wedlog/address/model/person/UniqueGuestListTest.java
  src/test/java/wedlog/address/testutil/GuestUtil.java
  src/test/java/wedlog/address/testutil/PersonUtil.java
  src/test/java/wedlog/address/testutil/VendorUtil.java
Labels: priority.High

#116 Fix vendor add bug
  src/main/java/wedlog/address/logic/Messages.java
  src/main/java/wedlog/address/logic/commands/VendorAddCommand.java
  src/main/java/wedlog/address/logic/parser/VendorAddCommandParser.java
  src/main/java/wedlog/address/model/person/DietaryRequirements.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandIntegrationTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandIntegrationTest.java
  src/test/java/wedlog/address/logic/parser/VendorAddCommandParserTest.java
  src/test/java/wedlog/address/testutil/TypicalVendors.java
Labels: priority.High

#119 Add table number field to `Guest`
  src/main/java/wedlog/address/logic/commands/GuestAddCommand.java
  src/main/java/wedlog/address/logic/parser/CliSyntax.java
  src/main/java/wedlog/address/logic/parser/GuestAddCommandParser.java
  src/main/java/wedlog/address/logic/parser/ParserUtil.java
  src/main/java/wedlog/address/model/person/Guest.java
  src/main/java/wedlog/address/model/person/TableNumber.java
  src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
  src/main/java/wedlog/address/ui/GuestCard.java
  src/main/java/wedlog/address/ui/StatisticsPanel.java
  src/main/resources/view/GuestListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateGuestAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicaGuestsAddressBook.json
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/parser/GuestAddCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/ParserUtilTest.java
  src/test/java/wedlog/address/model/person/GuestTest.java
  src/test/java/wedlog/address/model/person/TableNumberTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
  src/test/java/wedlog/address/testutil/GuestBuilder.java
  src/test/java/wedlog/address/testutil/GuestUtil.java
  src/test/java/wedlog/address/testutil/TypicalGuests.java
Labels: type.Story, priority.Medium

#121 Add `undo` and `redo` commands
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/wedlog/address/logic/commands/ClearCommand.java
  src/main/java/wedlog/address/logic/commands/DeleteCommand.java
  src/main/java/wedlog/address/logic/commands/EditCommand.java
  src/main/java/wedlog/address/logic/commands/GuestAddCommand.java
  src/main/java/wedlog/address/logic/commands/GuestDeleteCommand.java
  src/main/java/wedlog/address/logic/commands/RedoCommand.java
  src/main/java/wedlog/address/logic/commands/UndoCommand.java
  src/main/java/wedlog/address/logic/commands/VendorAddCommand.java
  src/main/java/wedlog/address/logic/commands/VendorDeleteCommand.java
  src/main/java/wedlog/address/logic/parser/AddressBookParser.java
  src/main/java/wedlog/address/model/Model.java
  src/main/java/wedlog/address/model/ModelManager.java
  src/main/java/wedlog/address/model/VersionedAddressBook.java
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/ClearCommandTest.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/DeleteCommandTest.java
  src/test/java/wedlog/address/logic/commands/EditCommandTest.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandIntegrationTest.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/GuestDeleteCommandTest.java
  src/test/java/wedlog/address/logic/commands/RedoCommandTest.java
  src/test/java/wedlog/address/logic/commands/UndoCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandIntegrationTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorDeleteCommandTest.java
  src/test/java/wedlog/address/logic/parser/AddressBookParserTest.java
  src/test/java/wedlog/address/model/VersionedAddressBookTest.java
Labels: type.Story, priority.Low

#124 Remove unused delete and list commands
  src/main/java/wedlog/address/logic/commands/DeleteCommand.java
  src/main/java/wedlog/address/logic/commands/ListCommand.java
  src/main/java/wedlog/address/logic/parser/AddressBookParser.java
  src/main/java/wedlog/address/logic/parser/DeleteCommandParser.java
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/DeleteCommandTest.java
  src/test/java/wedlog/address/logic/commands/ListCommandTest.java
  src/test/java/wedlog/address/logic/parser/AddressBookParserTest.java
  src/test/java/wedlog/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task, severity.Low

#123 Wrap optional fields in `Optional`
  src/main/java/wedlog/address/logic/commands/EditCommand.java
  src/main/java/wedlog/address/logic/parser/GuestAddCommandParser.java
  src/main/java/wedlog/address/logic/parser/ParserUtil.java
  src/main/java/wedlog/address/logic/parser/VendorAddCommandParser.java
  src/main/java/wedlog/address/model/person/Guest.java
  src/main/java/wedlog/address/model/person/Person.java
  src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
  src/main/java/wedlog/address/storage/JsonAdaptedPerson.java
  src/main/java/wedlog/address/ui/GuestCard.java
  src/main/java/wedlog/address/ui/VendorCard.java
  src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedPersonTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedVendorTest.java
  src/test/java/wedlog/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/wedlog/address/testutil/GuestBuilder.java
  src/test/java/wedlog/address/testutil/GuestUtil.java
  src/test/java/wedlog/address/testutil/PersonBuilder.java
  src/test/java/wedlog/address/testutil/PersonUtil.java
  src/test/java/wedlog/address/testutil/VendorBuilder.java
  src/test/java/wedlog/address/testutil/VendorUtil.java
Labels: priority.Medium

#128 Add `vendor edit`
  docs/UserGuide.md
  src/main/java/wedlog/address/commons/util/CollectionUtil.java
  src/main/java/wedlog/address/logic/Messages.java
  src/main/java/wedlog/address/logic/commands/VendorEditCommand.java
  src/main/java/wedlog/address/logic/parser/ParserUtil.java
  src/main/java/wedlog/address/logic/parser/VendorCommandParser.java
  src/main/java/wedlog/address/logic/parser/VendorEditCommandParser.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/EditVendorDescriptorTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorEditCommandTest.java
  src/test/java/wedlog/address/logic/parser/VendorCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/VendorEditCommandParserTest.java
  src/test/java/wedlog/address/model/person/UniqueVendorListTest.java
  src/test/java/wedlog/address/testutil/EditVendorDescriptorBuilder.java
  src/test/java/wedlog/address/testutil/TypicalVendors.java
Labels: type.Story, priority.Medium

#141 Change dietary requirements implementation
  src/main/java/wedlog/address/logic/Logic.java
  src/main/java/wedlog/address/logic/LogicManager.java
  src/main/java/wedlog/address/logic/parser/GuestAddCommandParser.java
  src/main/java/wedlog/address/logic/parser/ParserUtil.java
  src/main/java/wedlog/address/model/AddressBook.java
  src/main/java/wedlog/address/model/DietaryRequirementStatistics.java
  src/main/java/wedlog/address/model/Model.java
  src/main/java/wedlog/address/model/ModelManager.java
  src/main/java/wedlog/address/model/person/DietaryRequirements.java
  src/main/java/wedlog/address/model/person/Guest.java
  src/main/java/wedlog/address/model/person/UniqueGuestList.java
  src/main/java/wedlog/address/model/tag/DietaryRequirement.java
  src/main/java/wedlog/address/model/util/SampleDataUtil.java
  src/main/java/wedlog/address/storage/JsonAdaptedDietaryRequirement.java
  src/main/java/wedlog/address/storage/JsonAdaptedGuest.java
  src/main/java/wedlog/address/ui/GuestCard.java
  src/main/java/wedlog/address/ui/StatisticsPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GuestListCard.fxml
  src/main/resources/view/GuestListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateGuestAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalGuestsAddressBook.json
  src/test/java/wedlog/address/logic/LogicManagerTest.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
  src/test/java/wedlog/address/logic/parser/GuestAddCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/ParserUtilTest.java
  src/test/java/wedlog/address/model/AddressBookTest.java
  src/test/java/wedlog/address/model/DietaryRequirementStatisticsTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/person/DietaryRequirementsTest.java
  src/test/java/wedlog/address/model/person/GuestTest.java
  src/test/java/wedlog/address/model/person/UniqueGuestListTest.java
  src/test/java/wedlog/address/model/tag/DietaryRequirementTest.java
  src/test/java/wedlog/address/storage/JsonAdaptedGuestTest.java
  src/test/java/wedlog/address/testutil/GuestBuilder.java
  src/test/java/wedlog/address/testutil/GuestUtil.java
  src/test/java/wedlog/address/testutil/TypicalGuests.java
Labels: type.Enhancement, priority.High

#129 Implement `guest filter` and `vendor filter`
  src/main/java/wedlog/address/logic/Messages.java
  src/main/java/wedlog/address/logic/commands/GuestFilterCommand.java
  src/main/java/wedlog/address/logic/commands/GuestListCommand.java
  src/main/java/wedlog/address/logic/commands/VendorFilterCommand.java
  src/main/java/wedlog/address/logic/commands/VendorListCommand.java
  src/main/java/wedlog/address/logic/parser/GuestCommandParser.java
  src/main/java/wedlog/address/logic/parser/GuestFilterCommandParser.java
  src/main/java/wedlog/address/logic/parser/VendorCommandParser.java
  src/main/java/wedlog/address/logic/parser/VendorFilterCommandParser.java
  src/main/java/wedlog/address/model/Model.java
  src/main/java/wedlog/address/model/ModelManager.java
  src/main/java/wedlog/address/model/person/AddressPredicate.java
  src/main/java/wedlog/address/model/person/EmailPredicate.java
  src/main/java/wedlog/address/model/person/GuestRsvpPredicate.java
  src/main/java/wedlog/address/model/person/GuestTablePredicate.java
  src/main/java/wedlog/address/model/person/NamePredicate.java
  src/main/java/wedlog/address/model/person/PhonePredicate.java
  src/main/java/wedlog/address/model/person/Vendor.java
  src/test/java/wedlog/address/logic/commands/CommandTestUtil.java
  src/test/java/wedlog/address/logic/commands/GuestAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/GuestFilterCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorAddCommandTest.java
  src/test/java/wedlog/address/logic/commands/VendorFilterCommandTest.java
  src/test/java/wedlog/address/logic/parser/GuestCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/GuestFilterCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/VendorCommandParserTest.java
  src/test/java/wedlog/address/logic/parser/VendorFilterCommandParserTest.java
  src/test/java/wedlog/address/model/ModelManagerTest.java
  src/test/java/wedlog/address/model/person/AddressPredicateTest.java
  src/test/java/wedlog/address/model/person/EmailPredicateTest.java
  src/test/java/wedlog/address/model/person/GuestRsvpPredicateTest.java
  src/test/java/wedlog/address/model/person/GuestTablePredicateTest.java
  src/test/java/wedlog/address/model/person/NamePredicateTest.java
  src/test/java/wedlog/address/model/person/PhonePredicateTest.java
Labels: priority.Medium

#143 build.gradle: Enable assertions
  build.gradle
Labels: priority.High

#130 Update UG
  docs/UserGuide.md
  docs/favicon.ico
  docs/images/Ui.png
Labels: documentation, priority.Low

#144 DG: Add section on tracking guests and vendors
  docs/DeveloperGuide.md
  docs/diagrams/GuestClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#145 Update DG: filter feature
  docs/DeveloperGuide.md
  docs/diagrams/FilterGuestPredicateClassDiagram.puml
  docs/diagrams/FilterGuestSequenceDiagram.puml
  docs/diagrams/FilterGuestSequenceDiagramRef.puml
  docs/diagrams/FilterPersonPredicateClassDiagram.puml
  docs/diagrams/FilterVendorSequenceDiagram.puml
  docs/diagrams/FilterVendorSequenceDiagramRef.puml
Labels: documentation, priority.High

#146 DG: Add delete feature
  docs/DeveloperGuide.md
  docs/diagrams/DeleteExecuteSequenceDiagram.puml
  docs/diagrams/DeleteParseSequenceDiagram.puml
Labels: documentation, priority.High

#149 DG: Add edit feature
  docs/DeveloperGuide.md
  docs/diagrams/EditExecuteSequenceDiagram.puml
  docs/diagrams/EditParseSequenceDiagram.puml
Labels: documentation, priority.High

#151 Add ctrl+z and ctrl+y shortcuts
  src/main/java/wedlog/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Enhancement, priority.Medium

#154 UG: Add numbering
  docs/UserGuide.md
Labels: documentation

#162 Enhance UG
  docs/UserGuide.md
Labels: documentation

#164 Update ug
  docs/UserGuide.md
Labels: documentation, priority.Medium
